[project]
name = "aegisx"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Dhanavarshini T", email = "dhanavarshini19004@gmail.com" }
]
requires-python = ">=3.14"
dependencies = [
    "joblib>=1.5.3",
    "pandas>=3.0.5",
    "scikit-learn>=1.9.0",
]

[project.scripts]
aegisx = "aegisx:main"

[build-system]
requires = ["uv_build>=0.12.5,<0.13.0"]
build-backend = "uv_build"
